### ISSUE TITLE
way to disable the route referrer feature

### ISSUE THREAD

**Issue by craue** [codeconsortium/CCDNUserSecurityBundle#12]
I could need a way to disable this feature altogether. Maybe with

``` yaml
ccdn_user_security:
  route_referer: false
```

or

``` yaml
ccdn_user_security:
  route_referer:
    enabled: false
```
