### ISSUE TITLE
User Entity is never used

### ISSUE THREAD

**Issue by thkoch2001** [codeconsortium/CCDNUserSecurityBundle#25]
Hi,

we just integrated CCDNUserSecurityBundle into a legacy application where we do not yet use the FOSUserBundle, nor do we have a (doctrine) entity for our user class.

So we where stuck a bit, because we did not now, what value we could provide for this configuration key:

```
ccdn_user_security:
    entity:
        user:
            class: Acme\YourUserBundle\Entity\User # Required
```

After greping through the code we came to the conclusion that this configuration value is never used. So we left the example value in there and everything worked fine.

Is it right, that this configuration key should be removed from CCDNUserSecurityBundle
